### ISSUE TITLE
How to create a Login page before going to de side menu app and home page

### ISSUE THREAD

**Issue by dfleider** [MacKentoch/reactNativeReduxFastStarter#2]
Hello, I would like some help implementing this code. I'm trying to implement an login page that when the login suceed, then you enter to a kind of page that you implemented. Can you help me with that? I don't understand how did you use the navigator in your code. 

Also another question that I have is that I see that you have the Android and iOS code completely separated am I right? I'm doing an app that every component functions both in iOS and Android. The original side-bar implementation that your's base on have all the files in common, but I can see that yours is like separated. If i'm wrong please correct me.

Thanks!

dfleider

**Comment by MacKentoch** [comment]
Hi @dfleider,

Let me suggest you a login example here [#1](https://github.com/MacKentoch/reactNativeReduxFastStarter/issues/1#issuecomment-246308943).

This is simple way to implement login view.

In more complicated applications I may have to add another **upper navigator** (_so app content would be a content to this upper navigator_) but it is not often needed (_it depends your application_).

By the way, in React Native or even native mobile (_at least iOS I better know_) _you could have many navigator in a same application_. Navigator is not a regular component but it helps for transition and some kind routing. You aren't limited to only 1 navigator per application.

Concerning file and folder organisation, there is no best rule to follow.

The way I organise my code:
- I consider iOS and Android will never share 100% code
  - at least for the UI reason ->  iOS and Android app should distinct themselves by a different UI (_it is well known iOS users and Android users prefer same app does not look a clone in both platforms_).
  - BUT this is not a requirement, a lot of super star apps are absolutely identical in iOS and Android 
- I could have code in a single file for both platform 
  - then for specific cases just test current platform [see platform management](https://facebook.github.io/react-native/docs/platform-specific-code.html)
  - BUT to my mind it makes code a bit more complicated so that I better split into multiple files
  - ONCE again his is just my point of view and not an absolute truth to blindly follow (maybe you will be more successful by using a single file)
- I could avoid directory tree by naming files:
  - `FILENAME.ios.js` for iOS 
  - `FILENAME.android.js` for android
  - but just in my point of view I prefer avoiding long naming and I prefer directories
- And so on...

As you can see, you have numerous way to organise your code.

This repo is my way but maybe your way should be different for you to feel more comfortable.

**If you have all your components in the common directory, it may be a good decision to fusion iOS and Android code.**

> The best decision for code organisation will be your decision (_according to your personal preference, your team work, testing etc..._).

I hope I gave you answers you needed.

**Comment by dfleider** [comment]
Perfect! So I think all my components that I'm using are in the common directory so I'll see if I fusion both codes.
 Thank you!
