### ISSUE TITLE
Tiny vertical border showing different color

### ISSUE THREAD

**Issue by dfleider** [MacKentoch/reactNativeReduxFastStarter#3]
Hi!

I'm inserting an image to every window, but it shows in every window a small white column that I guess is from the back of the image. The image that i'm inserting has the following style:

  container: {
    flex: 1,
    width: null,
    height:null,
    paddingTop: 20,
    alignItems: 'center',
  },

Inside the Home component I have the following render:

`render() {
    return (
    <Image source={require('../../../common/img/background.png')} style={CommonStyles.container}>
      <View style={styles.container}>
        <Text>
        Home        
        </Text>
      </View>
    </Image>
    );
  }
}`

![img_1899](https://cloud.githubusercontent.com/assets/12035186/18821252/f32595e8-837a-11e6-80f4-040c1888a15d.PNG)

If you press on the above screenshot you will be able to see the white vertical border

Thanks again!

**Comment by MacKentoch** [comment]
Maybe you should try to set `resizeMode` Image prop ([see](https://facebook.github.io/react-native/docs/image.html#resizemode)).

It can also be induced by styling from container (I mean App). 
So try to remove navigator borders for example.

I can't be precise since I don't have all code.
But in such cases (I mean it happens often to everyone 😄 ) just fix by adjusting 'till you fix it.

I'm confident you will fix it.

**Comment by dfleider** [comment]
Yes, the navigator had a small border width. Thanks!
