### ISSUE TITLE
Information Bar on the top

### ISSUE THREAD

**Issue by dfleider** [MacKentoch/reactNativeReduxFastStarter#4]
Hi again!

I would like to be able to see the information (hour, carrier, battery, etc) on the top of the screen. I can see that the info is not being showed because of the white background color. Is it possible to change this color? where? That would solve the entire problem.

Thanks! this side bar has helped me a lot

**Comment by MacKentoch** [comment]
Hi @dfleider,

In `App.js`, I set status bar style as light.

Comment this line (in render method) or just update to what you need ([more info in React Native website](https://facebook.github.io/react-native/docs/statusbar.html))

``` javascript
StatusBar.setBarStyle('light-content', true);
```

By the way, it does not require to be in render method. 
I may move it since it does not give the best performance there.
Thank you for pointing this.

_Note: status bar is specific to iOS_

**Comment by dfleider** [comment]
Thanks!!
